### ISSUE TITLE
System.AggregateException and  InvalidOperationException exception

### ISSUE THREAD

**Issue by codebee** [berkayyerdelen/Dapper.WebApi#1]
Hi @berkayyerdelen 

I tried to run the project. However I got below errors. Please help me to sort this out.

System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Dapper.WebApi.Services.IProductRepository Lifetime: Transient ImplementationType: Dapper.WebApi.Services.ProductRepository': Unable to resolve service for type 'Dapper.WebApi.Services.ExecuteCommands.IExecuters' while attempting to activate 'Dapper.WebApi.Services.ProductRepository'.)'

InvalidOperationException: Unable to resolve service for type 'Dapper.WebApi.Services.ExecuteCommands.IExecuters' while attempting to activate 'Dapper.WebApi.Services.ProductRepository'.

thanks.

**Comment by berkayyerdelen** [comment]
Hi @codebee 
Actually the current version of the project a bit different than medium post since I made some changes. 

InvalidOperationException: Unable to resolve service for type 'Dapper.WebApi.Services.ExecuteCommands.IExecuters' while attempting to activate 'Dapper.WebApi.Services.ProductRepository'.

Here you can see that  "' Dapper.WebApi.Services.ExecuteCommands.**IExecuters**' while attempting to activate " bold text needs to be injected into ConfigureServices.

I have made the changes and committed the working version.
On the other hand, I have upgraded the project version to 3.1.

Thanks
