### ISSUE TITLE
CommandText and ICommandText

### ISSUE THREAD

**Issue by zaktecs** [berkayyerdelen/Dapper.WebApi#2]
This is just a question: 

Does it mean that I have to create this (ICommandText and ICommandText) for each table in the database or is there a generic way to write this

Kind Regards,

Zak

**Comment by berkayyerdelen** [comment]
Actually It depends, I'd use the all commands in the ICommandText but it will cause some management and maintain problems in the future so that you might separate the domain commands into different Interfaces such as  "IProductCommandText"  would be much cleaner.
In addition that you might see the some patterns like Generic Repository etc. I would avoid using it since they're anti-pattern but it still considerable.

Regards
Berkay

**Comment by zaktecs** [comment]
Thanks for your response
